/**
 * Ignore, generated-code, and secret-exclusion rules
 * (REPOSITORY_PROCESSOR_SERVICE_PLAN.md "Ignore and Exclusion Rules",
 * DATA_RETENTION_AND_PRIVACY.md "Excluded file patterns", RULES.md #14).
 * Repository `.gitignore` is deliberately not consulted — see the plan doc.
 */

export type SkipReason = "ignored" | "binary" | "too_large" | "excluded_secret" | "generated";

const IGNORED_DIRECTORIES = new Set([
  ".git",
  "node_modules",
  "dist",
  "build",
  "out",
  ".next",
  ".nuxt",
  ".turbo",
  "coverage",
  "vendor",
  "target",
  "__pycache__",
  ".venv",
]);

const IGNORED_FILENAMES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "Cargo.lock",
  "Gemfile.lock",
  "composer.lock",
  "poetry.lock",
]);

const IGNORED_EXTENSIONS = new Set([".min.js", ".map"]);

/** DATA_RETENTION_AND_PRIVACY.md "Excluded file patterns" — never written to S3, never in the inventory, never embedded. */
const SECRET_PATTERNS: RegExp[] = [
  /^\.env(\..+)?$/i,
  /\.env$/i,
  /\.pem$/i,
  /\.key$/i,
  /\.p12$/i,
  /\.pfx$/i,
  /\.jks$/i,
  /\.keystore$/i,
  /^id_rsa(\..+)?$/i,
  /^id_ed25519(\..+)?$/i,
  /\.ppk$/i,
  /^\.npmrc$/i,
  /^\.netrc$/i,
  /^\.pgpass$/i,
  /^\.htpasswd$/i,
  /^credentials(\.json)?$/i,
  /^service-account.*\.json$/i,
  /\.tfstate(\.backup)?$/i,
  /^secrets\..+$/i,
  /secrets\.ya?ml$/i,
];

const GENERATED_MARKERS = [/@generated\b/, /Code generated by/i];
/** Only worth scanning the first slice of a file for a generated-code marker — it's always near the top. */
const GENERATED_MARKER_SCAN_BYTES = 512;

/** A directory name anywhere in the path (not just the immediate parent) makes the whole entry ignored. */
export function isIgnoredPath(pathSegments: string[]): boolean {
  return pathSegments.slice(0, -1).some((segment) => IGNORED_DIRECTORIES.has(segment));
}

export function isIgnoredFilename(filename: string): boolean {
  if (IGNORED_FILENAMES.has(filename)) return true;
  return [...IGNORED_EXTENSIONS].some((ext) => filename.endsWith(ext));
}

export function isSecretFile(filename: string): boolean {
  return SECRET_PATTERNS.some((pattern) => pattern.test(filename));
}

/** Null byte in the first 8 KB is the standard cheap binary heuristic — matches the plan doc exactly. */
export function looksBinary(sample: Buffer): boolean {
  const limit = Math.min(sample.length, 8192);
  for (let i = 0; i < limit; i += 1) {
    if (sample[i] === 0) return true;
  }
  return false;
}

export function looksGenerated(sample: Buffer): boolean {
  const head = sample.subarray(0, GENERATED_MARKER_SCAN_BYTES).toString("utf8");
  return GENERATED_MARKERS.some((marker) => marker.test(head));
}
