import { describe, expect, it } from "vitest";
import { isIgnoredFilename, isIgnoredPath, isSecretFile, looksBinary, looksGenerated } from "./ignore-rules";

describe("isIgnoredPath", () => {
  it("ignores anything under node_modules, dist, .git, etc.", () => {
    expect(isIgnoredPath(["node_modules", "left-pad", "index.js"])).toBe(true);
    expect(isIgnoredPath(["src", "dist", "bundle.js"])).toBe(true);
    expect(isIgnoredPath([".git", "HEAD"])).toBe(true);
    expect(isIgnoredPath(["vendor", "lib.php"])).toBe(true);
  });

  it("does not ignore a normal source path", () => {
    expect(isIgnoredPath(["src", "modules", "app.ts"])).toBe(false);
  });
});

describe("isIgnoredFilename", () => {
  it("ignores lockfiles and minified/sourcemap files", () => {
    expect(isIgnoredFilename("package-lock.json")).toBe(true);
    expect(isIgnoredFilename("pnpm-lock.yaml")).toBe(true);
    expect(isIgnoredFilename("bundle.min.js")).toBe(true);
    expect(isIgnoredFilename("app.js.map")).toBe(true);
  });

  it("does not ignore a normal filename", () => {
    expect(isIgnoredFilename("app.ts")).toBe(false);
  });
});

describe("isSecretFile", () => {
  it("matches every documented secret pattern", () => {
    expect(isSecretFile(".env")).toBe(true);
    expect(isSecretFile(".env.production")).toBe(true);
    expect(isSecretFile("server.pem")).toBe(true);
    expect(isSecretFile("private.key")).toBe(true);
    expect(isSecretFile("id_rsa")).toBe(true);
    expect(isSecretFile("id_rsa.pub")).toBe(true);
    expect(isSecretFile(".npmrc")).toBe(true);
    expect(isSecretFile(".netrc")).toBe(true);
    expect(isSecretFile("credentials")).toBe(true);
    expect(isSecretFile("credentials.json")).toBe(true);
    expect(isSecretFile("service-account-prod.json")).toBe(true);
    expect(isSecretFile("terraform.tfstate")).toBe(true);
    expect(isSecretFile("secrets.yaml")).toBe(true);
  });

  it("does not flag ordinary source files", () => {
    expect(isSecretFile("app.ts")).toBe(false);
    expect(isSecretFile("environment.ts")).toBe(false);
  });
});

describe("looksBinary", () => {
  it("detects a null byte in the first 8 KB", () => {
    expect(looksBinary(Buffer.from([0x48, 0x65, 0x00, 0x6c, 0x6f]))).toBe(true);
  });

  it("treats plain UTF-8 text as non-binary", () => {
    expect(looksBinary(Buffer.from("export const x = 1;\n", "utf8"))).toBe(false);
  });
});

describe("looksGenerated", () => {
  it("detects a leading @generated marker", () => {
    expect(looksGenerated(Buffer.from("// @generated by some-tool\nexport {}\n"))).toBe(true);
  });

  it("detects a leading 'Code generated by' marker", () => {
    expect(looksGenerated(Buffer.from("// Code generated by protoc-gen-go. DO NOT EDIT.\n"))).toBe(true);
  });

  it("does not flag ordinary source content", () => {
    expect(looksGenerated(Buffer.from("export const x = 1;\n"))).toBe(false);
  });
});
